@extends('frontend.layout')

@section('content')

    <div class="jumbotron jumbotron-fluid" data-center="background-size: 100%;" data-top-bottom="background-size: 110%;" style="background: rgb(50, 50, 50) !important;padding:0">
        <div class="container">
            <!-- jumbo-heading -->
            <div class="jumbo-heading" data-aos="fade-up">
                <h1>Privacy Policy</h1>
                <!-- Breadcrumbs -->
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="{{ url(FRONTENDURL) }}">Home</a></li>
                        <li class="breadcrumb-item active" aria-current="page">Privacy Policy</li>
                    </ol>
                </nav>
                <!-- /breadcrumb -->
            </div>
            <!-- /jumbo-heading -->
        </div>
        <!-- /container -->
    </div>

    <div class="page container" style="padding-top:50px;">
        <div class="row">
            <!-- page with sidebar starts -->
            <div class="col-lg-12 page-with-sidebar">
                <div class="col-lg-12">
                    <h2>Privacy Policy</h2>
                    <hr class="small-divider left">
                    <p class="mt-4">
                        <strong>1. Introduction</strong><br /><br />
                        Welcome to <strong>Untame Pets.</strong><br /><br />
                        <strong>Untame Pets</strong> (“us”, “we”, or “our”) operates <strong>www.untame.pet</strong>
                        (hereinafter referred to as <strong>“Service”</strong>).<br /><br />
                        Our Privacy Policy governs your visit to <strong>www.untame.pet,</strong> and explains how we
                        collect, safeguard and disclose information that results from your use of our Service.<br /><br />

                        We use your data to provide and improve Service. By using Service, you agree to the collection and
                        use of information in accordance with this policy. Unless otherwise defined in this
                        Privacy Policy, the terms used in this Privacy Policy have the same meanings as in our Terms and
                        Conditions.<br /><br />

                        Our Terms and Conditions (<strong>“Terms”</strong>) govern all use of our Service and together with
                        the Privacy Policy constitutes your agreement with us (<strong>“agreement” </strong>).<br /><br />

                        <strong>2. Definitions</strong><br /><br />
                        <strong>SERVICE</strong> means the www.untame.pet website operated by Untame Pets.<br /><br />
                        <strong>PERSONAL DATA</strong> means data about a living individual who can be identified from those
                        data (or from those and other information either in our possession or likely to come into our
                        possession).<br /><br />
                        <strong>USAGE DATA</strong> is data collected automatically either generated by the use of Service
                        or from Service infrastructure itself (for example, the duration of a page visit).<br /><br />
                        <strong>COOKIES</strong> are small files stored on your device (computer or mobile
                        device).<br /><br />
                        <strong>DATA CONTROLLER</strong> means a natural or legal person who (either alone or jointly or in
                        common with other persons) determines the purposes for which and the manner in which any personal
                        data are, or are to be, processed. For the purpose of this Privacy Policy, we are a Data Controller
                        of your data.<br /><br />
                        <strong>DATA PROCESSORS (OR SERVICE PROVIDERS)</strong> means any natural or legal person who
                        processes the data on behalf of the Data Controller. We may use the services of various Service
                        Providers in order to process your data more effectively.<br /><br />
                        <strong>DATA SUBJECT</strong> is any living individual who is the subject of Personal
                        Data.<br /><br />
                        <strong>THE USER</strong> is the individual using our Service. The User corresponds to the Data
                        Subject, who is the subject of Personal Data.<br /><br />

                        <strong>3. Information Collection and Use</strong><br /><br />
                        We collect several different types of information for various purposes to provide and improve our
                        Service to you.<br /><br />

                        <strong>4. Types of Data Collected</strong><br /><br />
                        <strong>Personal Data</strong><br /><br />
                        While using our Service, we may ask you to provide us with certain personally identifiable
                        information that can be used to contact or identify you <strong>(“Personal Data”)</strong>.
                        Personally identifiable information may include, but is not limited to:<br />
                        0.1. Email address<br />
                        0.2. First name and last name<br />
                        0.3. Phone number<br />
                        0.4. Address, Country, State, Province, ZIP/Postal code, City<br />
                        0.5. Cookies and Usage Data<br /><br />
                        We may use your Personal Data to contact you with newsletters, marketing or promotional materials
                        and other information that may be of interest to you. You may opt out of receiving any, or all, of
                        these communications from us by following the unsubscribe link.<br /><br />
                        <strong>Usage Data</strong><br /><br />
                        We may also collect information that your browser sends whenever you visit our Service or when you
                        access Service by or through any device <strong>(“Usage Data”)</strong>.<br /><br />
                        This Usage Data may include information such as your computer’s Internet Protocol address (e.g. IP
                        address), browser type, browser version, the pages of our Service that you visit, the time and date
                        of your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                        When you access Service with a device, this Usage Data may include information such as the type of
                        device you use, your device unique ID, the IP address of your device, your device operating system,
                        the type of Internet browser you use, unique device identifiers and other diagnostic data.
                        <strong>Location Data</strong><br /><br />
                        We may use and store information about your location if you give us permission to do so
                        <strong>(“Location Data”)</strong>. We use this data to provide features of our Service, to improve
                        and customize our Service.<br /><br />
                        You can enable or disable location services when you use our Service at any time by way of your
                        device settings.<br /><br />
                        <strong>Tracking Cookies Data</strong><br /><br />
                        We use cookies and similar tracking technologies to track the activity on our Service and we hold
                        certain information.<br /><br />
                        Cookies are files with a small amount of data which may include an anonymous unique identifier.
                        Cookies are sent to your browser from a website and stored on your device. Other tracking
                        technologies are also used such as beacons, tags and scripts to collect and track information and to
                        improve and analyze our Service.<br /><br />
                        You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent.
                        However, if you do not accept cookies, you may not be able to use some portions of our
                        Service.<br /><br />
                        Examples of Cookies we use:<br />
                        <strong>0.1. Session Cookies:</strong> We use Session Cookies to operate our Service.<br />
                        <strong>0.2. Preference Cookies:</strong> We use Preference Cookies to remember your preferences and
                        various settings.<br />
                        <strong> 0.3. Security Cookies:</strong> We use Security Cookies for security purposes.<br />
                        <strong>0.4. Advertising Cookies:</strong> Advertising Cookies are used to serve you
                        with<br /><br />
                        advertisements that may be relevant to you and your interests.<br /><br />
                        <strong>Other Data</strong><br /><br />
                        While using our Service, we may also collect the following information: sex, age, date of birth,
                        place of birth, passport details, citizenship, registration at place of residence and actual
                        address, telephone number (work, mobile), details of documents on education, qualification,
                        professional training, employment agreements, NDA agreements, information on bonuses and
                        compensation, information on marital status, family members, social security (or other taxpayer
                        identification) number, office location and other data.<br /><br />

                        <strong>5. Use of Data</strong><br /><br />
                        Untame Pets uses the collected data for various purposes:<br />
                        0.1. to provide and maintain our Service;<br />
                        0.2. to notify you about changes to our Service;<br />
                        0.3. to allow you to participate in interactive features of our Service when you choose to do
                        so;<br />
                        0.4. to provide customer support;<br />
                        0.5. to gather analysis or valuable information so that we can improve our Service;<br />
                        0.6. to monitor the usage of our Service;<br />
                        0.7. to detect, prevent and address technical issues;<br />
                        0.8. to fulfil any other purpose for which you provide it;<br />
                        0.9. to carry out our obligations and enforce our rights arising from any contracts entered into
                        between you and us, including for billing and collection;<br />
                        0.10. to provide you with notices about your account and/or subscription, including expiration and
                        renewal notices, email-instructions, etc.;<br />
                        0.11. to provide you with news, special offers and general information about other goods, services
                        and events which we offer that are similar to those that you have already purchased or enquired
                        about unless you have opted not to receive such information;<br />
                        0.12. in any other way we may describe when you provide the information;<br />
                        0.13. for any other purpose with your consent.<br /><br />

                        <strong>6. Retention of Data</strong><br /><br />
                        We will retain your Personal Data only for as long as is necessary for the purposes set out in this
                        Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our
                        legal obligations (for example, if we are required to retain your data to comply with applicable
                        laws), resolve disputes, and enforce our legal agreements and policies.<br /><br />
                        We will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for
                        a shorter period, except when this data is used to strengthen the security or to improve the
                        functionality of our Service, or we are legally obligated to retain this data for longer time
                        periods.<br /><br />

                        <strong>7. Transfer of Data</strong><br /><br />
                        Your information, including Personal Data, may be transferred to – and maintained on – computers
                        located outside of your state, province, country or other governmental jurisdiction where the data
                        protection laws may differ from those of your jurisdiction.<br /><br />
                        If you are located outside India and choose to provide information to us, please note that we
                        transfer the data, including Personal Data, to India and process it there.<br /><br />
                        Your consent to this Privacy Policy followed by your submission of such information represents your
                        agreement to that transfer.<br /><br />
                        Untame Pets will take all the steps reasonably necessary to ensure that your data is treated
                        securely and in accordance with this Privacy Policy and no transfer of your Personal Data will take
                        place to an organisation or a country unless there are adequate controls in place including the
                        security of your data and other personal information.<br /><br />

                        <strong>8. Disclosure of Data</strong><br /><br />
                        We may disclose personal information that we collect, or you provide:<br /><br />
                        <strong>0.1. Disclosure for Law Enforcement.</strong><br />
                        Under certain circumstances, we may be required to disclose your Personal Data if required to do so
                        by law or in response to valid requests by public authorities.<br />
                        <strong>0.2. Business Transaction.</strong><br />
                        If we or our subsidiaries are involved in a merger, acquisition or asset sale, your Personal Data
                        may be transferred.<br />
                        <strong>0.3. Other cases. We may disclose your information also:</strong><br />
                        0.3.1. to our subsidiaries and affiliates;<br />
                        0.3.2. to contractors, service providers, and other third parties we use to support our
                        business;<br />
                        0.3.3. to fulfill the purpose for which you provide it;<br />
                        0.3.4. for the purpose of including your company’s logo on our website;<br />
                        0.3.5. for any other purpose disclosed by us when you provide the information;<br />
                        0.3.6. with your consent in any other cases;<br />
                        0.3.7. if we believe disclosure is necessary or appropriate to protect the rights, property, or
                        safety of the Company, our customers, or others.<br/><br/>

                        <strong>9. Security of Data</strong><br/><br/>
                        The security of your data is important to us but remember that no method of transmission over the
                        Internet or method of electronic storage is 100% secure. While we strive to use commercially
                        acceptable means to protect your Personal Data, we cannot guarantee its absolute security.<br/><br/>

                        <strong>10. Your Rights Over Your Data </strong><br/><br/>
                        We aim to take reasonable steps to allow you to correct, amend, delete, or limit the use of your
                        Personal Data.<br/><br/>
                        If you wish to be informed what Personal Data we hold about you and if you want it to be removed
                        from our systems, please email us at <strong>woof@untame.pet.</strong><br/><br/>
                        In certain circumstances, you have the following data protection rights:<br/>
                        0.1. the right to access, update or to delete the information we have on you;<br/>
                        0.2. the right of rectification. You have the right to have your information rectified if that
                        information is inaccurate or incomplete;<br/>
                        0.3. the right to object. You have the right to object to our processing of your Personal Data;<br/>
                        0.4. the right of restriction. You have the right to request that we restrict the processing of your
                        personal information;<br/>
                        0.5. the right to data portability. You have the right to be provided with a copy of your Personal
                        Data in a structured, machine-readable and commonly used format;<br/>
                        0.6. the right to withdraw consent. You also have the right to withdraw your consent at any time
                        where we rely on your consent to process your personal information;<br/>
                        Please note that we may ask you to verify your identity before responding to such requests. Please
                        note, we may not able to provide Service without some necessary data.<br/><br/>

                        <strong>11. Service Providers</strong><br/><br/>
                        We may employ third party companies and individuals to facilitate our Service (“Service Providers”),
                        provide Service on our behalf, perform Service-related services or assist us in analysing how our
                        Service is used.<br/><br/>
                        These third parties have access to your Personal Data only to perform these tasks on our behalf and
                        are obligated not to disclose or use it for any other purpose.<br/><br/>

                        <strong>12. Analytics</strong><br/><br/>
                        We may use third-party Service Providers to monitor and analyse the use of our Service.<br/><br/>

                        <strong>13. CI/CD tools</strong><br/><br/>
                        We may use third-party Service Providers to automate the development process of our Service.<br/><br/>

                        <strong>14. Behavioural Remarketing</strong><br/><br/>
                        We may use remarketing services to advertise on third party websites to you after you visited our
                        Service. We and our third-party vendors use cookies to inform, optimise and serve ads based on your
                        past visits to our Service.<br/><br/>

                        <strong>15. Payments</strong><br/><br/>
                        We may provide paid products and/or services within Service. In that case, we use third-party
                        services for payment processing (e.g. payment processors).<br/><br/>
                        We will not store or collect your payment card details. That information is provided directly to our
                        third-party payment processors whose use of your personal information is governed by their Privacy
                        Policy. These payment processors adhere to the standards set by PCI-DSS as managed by the PCI
                        Security Standards Council, which is a joint effort of brands like Visa, Mastercard, American
                        Express and Discover. PCI-DSS requirements help ensure the secure handling of payment information.<br/><br/>

                        <strong>16. Links to Other Sites</strong><br/><br/>
                        Our Service may contain links to other sites that are not operated by us. If you click a third party
                        link, you will be directed to that third party’s site. We strongly advise you to review the Privacy
                        Policy of every site you visit.<br/><br/>
                        We have no control over and assume no responsibility for the content, privacy policies or practices
                        of any third party sites or services.<br/><br/>

                        <strong>17. Children’s Privacy</strong><br/><br/>
                        Our Services are not intended for use by children under the age of 18 (<strong>“Child”</strong> or
                        <strong>“Children”</strong>).<br/><br/>
                        We do not knowingly collect personally identifiable information from Children under 18. If you
                        become aware that a Child has provided us with Personal Data, please contact us. If we become aware
                        that we have collected Personal Data from Children without verification of parental consent, we take
                        steps to remove that information from our servers.<br/><br/>

                        <strong>18. Changes to This Privacy Policy</strong><br/><br/>
                        We may update our Privacy Policy from time to time. We will notify you of any changes by posting the
                        new Privacy Policy on this page.<br/><br/>
                        We will let you know via email and/or a prominent notice on our Service, prior to the change
                        becoming effective and update “effective date” at the top of this Privacy Policy.<br/><br/>
                        You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy
                        Policy are effective when they are posted on this page.<br/><br/>

                        <strong>19. Contact Us</strong><br/><br/>
                        If you have any questions about this Privacy Policy, please contact us by email:
                        <strong>woof@untame.pet.</strong>

                    </p>
                </div>
            </div>
        </div>
    </div>

@stop
